
# Site settings
title: Fernanda Pincheira
email: fernanda.pincheira@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Página personal de Fernanda Pincheira</a>
baseurl: "" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site
logo: "/assets/img/istockphoto-1131741622-170667a.jpg"

# Build settings
paginate: 0
paginate_path: "/blog/page:num/"
markdown: kramdown
sass:
    sass_dir: assets/css/sass
    style: compressed

gems:
  - jekyll-gist
  - jekyll-paginate